
package mypackage.CXFsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NetbarServices", targetNamespace = "http://service.netbar.temple.xiaojf.cn")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface NetbarServices {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
//    @WebResult(targetNamespace = "http://service.netbar.temple.xiaojf.cn")
//    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.netbar.temple.xiaojf.cn", className = "CXFsClient.SayHello")
//    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.netbar.temple.xiaojf.cn", className = "CXFsClient.SayHelloResponse")
        @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.netbar.temple.xiaojf.cn", className = "NetbarServices")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.netbar.temple.xiaojf.cn", className = "NetbarServices")
    public String sayHello(
        @WebParam(name = "userName"
//                , targetNamespace = "http://service.netbar.temple.xiaojf.cn"
            )
        String userName);

}
