
package mypackage.CXFsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NetbarServices", targetNamespace = "http://service.netbar.temple.xiaojf.cn", wsdlLocation = "http://localhost:8070/services/hanhan?wsdl")
public class NetbarServices_Service
    extends Service
{

    private final static URL NETBARSERVICES_WSDL_LOCATION;
    private final static WebServiceException NETBARSERVICES_EXCEPTION;
    private final static QName NETBARSERVICES_QNAME = new QName("http://service.netbar.temple.xiaojf.cn", "NetbarServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8070/services/hanhan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETBARSERVICES_WSDL_LOCATION = url;
        NETBARSERVICES_EXCEPTION = e;
    }

    public NetbarServices_Service() {
        super(__getWsdlLocation(), NETBARSERVICES_QNAME);
    }

    public NetbarServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NETBARSERVICES_QNAME, features);
    }

    public NetbarServices_Service(URL wsdlLocation) {
        super(wsdlLocation, NETBARSERVICES_QNAME);
    }

    public NetbarServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NETBARSERVICES_QNAME, features);
    }

    public NetbarServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetbarServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NetbarServices
     */
    @WebEndpoint(name = "NetbarServicesImplPort")
    public NetbarServices getNetbarServicesImplPort() {
        return super.getPort(new QName("http://service.netbar.temple.xiaojf.cn", "NetbarServicesImplPort"), NetbarServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetbarServices
     */
    @WebEndpoint(name = "NetbarServicesImplPort")
    public NetbarServices getNetbarServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.netbar.temple.xiaojf.cn", "NetbarServicesImplPort"), NetbarServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETBARSERVICES_EXCEPTION!= null) {
            throw NETBARSERVICES_EXCEPTION;
        }
        return NETBARSERVICES_WSDL_LOCATION;
    }

}
